### ISSUE TITLE
Querying Super Bowl 2014 throws TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by wilcollins** [BurntSushi/nflgame#127]
````
>>> nflgame.games([2014], [4], None, None, 'POST', False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wc/anaconda/lib/python2.7/site-packages/nflgame/__init__.py", line 220, in games
    return list(games_gen(year, week, home, away, kind, started))
TypeError: 'NoneType' object is not iterable
````

**Comment by BurntSushi** [comment]
Unfortunately, NFL.com considers the Super Bowl to be week 5 in the postseason:

```
>>> nflgame.games([2014], [5], None, None, 'POST', False)
[<nflgame.game.Game object at 0x7fb401dac910>]
```

**Comment by wilcollins** [comment]
Is this new in 2014?

From your docs :
````
So the wild card round is week 1, the divisional round is week 2, the conference round is week 3 and the Super Bowl is week 4.
````

And from 2012 & 2013:
````
>>> nflgame.games([2013], [5], None, None, 'POST', False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wc/anaconda/lib/python2.7/site-packages/nflgame/__init__.py", line 220, in games
    return list(games_gen(year, week, home, away, kind, started))
TypeError: 'NoneType' object is not iterable
>>> nflgame.games([2012], [5], None, None, 'POST', False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wc/anaconda/lib/python2.7/site-packages/nflgame/__init__.py", line 220, in games
    return list(games_gen(year, week, home, away, kind, started))
TypeError: 'NoneType' object is not iterable
````

**Comment by wilcollins** [comment]
If it's week 5 going forward, that's easy enough to code around, but it would be helpful to have it documented somewhere

**Comment by BurntSushi** [comment]
It looks like it did change in 2014. A PR for fixing the docs would be most welcome. :-)
