### ISSUE TITLE
AttributeError: 'module' has no attribute 'live'

### ISSUE THREAD

**Issue by jimmcnulty41** [BurntSushi/nflgame#133]
The error comes from sched.py line 40. 

Here is the full traceback:

Traceback (most recent call last):

  File "<ipython-input-7-c16d8f9d4fcc>", line 1, in <module>
    runfile('C:/Users/James/Documents/Python Scripts/NFL/nfl_test1.py', wdir='C:/Users/James/Documents/Python Scripts/NFL')

  File "C:\Program Files (x86)\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 580, in runfile
    execfile(filename, namespace)

  File "C:/Users/James/Documents/Python Scripts/NFL/nfl_test1.py", line 8, in <module>
    import nflgame

  File "C:\Program Files (x86)\Anaconda\lib\site-packages\nflgame\__init__.py", line 89, in <module>
    import nflgame.game

  File "C:\Program Files (x86)\Anaconda\lib\site-packages\nflgame\game.py", line 12, in <module>
    import nflgame.sched

  File "C:\Program Files (x86)\Anaconda\lib\site-packages\nflgame\sched.py", line 47, in <module>
    games, last_updated = _create_schedule()

  File "C:\Program Files (x86)\Anaconda\lib\site-packages\nflgame\sched.py", line 40, in _create_schedule
    year, week = nflgame.live.current_year_and_week()

AttributeError: 'module' object has no attribute 'live'

**Comment by BurntSushi** [comment]
I don't know what the problem is here. Maybe you have a borked installation? What are the contents of the `C:\Program Files (x86)\Anaconda\lib\site-packages\nflgame\` directory? What happens if you run `python -c 'import nflgame.live'`?

**Comment by Mosetsfire84** [comment]
Was this ever resolved? I am encountering the same error. I do not have the program files folder listed above. is this needed?

**Comment by BurntSushi** [comment]
@Mosetsfire84 Please provide more information. I cannot help you if you don't provide enough information. For example, are you actually getting exactly the same error message? My comment above was specifically tailored to the error message given.

Please include the following:

* The source code of the Python program you're running.
* The command you're using to invoke it.
* The full output of the program when you run it.

The error message "'module object has no attribute 'live'" is indicative of a problem in your installation or environment somewhere. The only way to debug this is to provide as much information about your environment as possible.
