### ISSUE TITLE
import nflgame failure

### ISSUE THREAD

**Issue by Captain-Gerard** [BurntSushi/nflgame#146]
I have a 64 bit system and I got this error while attempting a program.  I am a total noob at this...

>>> import nflgame
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import nflgame
  File "C:\Users\Captain Gerard\AppData\Local\Programs\Python\Python35-32\lib\site-packages\nflgame\__init__.py", line 89, in <module>
    import nflgame.game
  File "C:\Users\Captain Gerard\AppData\Local\Programs\Python\Python35-32\lib\site-packages\nflgame\game.py", line 8, in <module>
    import urllib2
ImportError: No module named 'urllib2'

**Comment by ochawkeye** [comment]
'nflgame' is Python 2.x only.  You have Python 3.5.

**Comment by Captain-Gerard** [comment]
Thank you
