### ISSUE TITLE
Enable an offline mode

### ISSUE THREAD

**Issue by mjcorriere** [BurntSushi/nflgame#154]
When importing the nflgame module for the first time, I get this error:

import nflgame
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python27\lib\site-packages\nflgame\__init__.py", line 89, in <module>
    import nflgame.game
  File "c:\python27\lib\site-packages\nflgame\game.py", line 12, in <module>
    import nflgame.sched
  File "c:\python27\lib\site-packages\nflgame\sched.py", line 47, in <module>
    games, last_updated = _create_schedule()
  File "c:\python27\lib\site-packages\nflgame\sched.py", line 40, in _create_schedule
    year, week = nflgame.live.current_year_and_week()
  File "c:\python27\lib\site-packages\nflgame\live.py", line 115, in current_year_and_week
    _update_week_number()
  File "c:\python27\lib\site-packages\nflgame\live.py", line 358, in _update_week_number
    dom = xml.parse(urllib2.urlopen(_CUR_SCHEDULE, timeout=5))
  File "c:\python27\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "c:\python27\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "c:\python27\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "c:\python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "c:\python27\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error timed out>

I am positive this is due to being behind my company's proxy. Is it possible to use nflgame in an 'offline mode' such that it doesn't require internet connectivity? I would like to be able to play around with the data that comes with nflgame and am not immediately interested in the latest data.

Thanks!

**Comment by andr3w321** [comment]
Try using https://github.com/BurntSushi/nfldb

**Comment by BurntSushi** [comment]
`nflgame` isn't very mindful of "offline" mode. You might be able to hack its source a little bit to make it work, but `nfldb` is definitely the better solution since you'll only ever hit your DB. (Only `nfldb-update` needs internet access.)
