### ISSUE TITLE
Post season data retrieval. 

### ISSUE THREAD

**Issue by hackerDEpandas** [BurntSushi/nflgame#191]
Trying to get the first week of the playoffs of the 2015 season by using the following:
```
import nflgame as nf
games = nf.games(2015, week = 1, kind = 'POST')
```
and I get the following error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nflgame\__init__.py", line 228, in games
    return list(games_gen(year, week, home, away, kind, started))
TypeError: 'NoneType' object is not iterable
```
Any help on this would be greatly appreciated!

**Comment by ochawkeye** [comment]
If you are running an old version of 'nflgame' your schedule URL is
probably not pointed to the correct nfl.com URL. Try updating to the latest
'nflgame'.

**Comment by drwofle21** [comment]
Was this resolved? I am having a similar problem, I am unable to retrieve week 2 data for the 2015 post season. I tried updating 

```python
import nflgame
games = nflgame.games(2015, week=2, kind='POST')
plays = nflgame.combine_plays(games)
```
The code above results in an error: TypeError: 'NoneType' object is not iterable

However, when the week is set to either 1 or 3 I can retrieve the game.

I must add that a double checked nflgame.VERSION and I see '1.2.19'
