### ISSUE TITLE
Playoff 2015 data after week 1 not available ?

### ISSUE THREAD

**Issue by kpelechrinis** [BurntSushi/nflgame#193]
Hi,

I was just wondering whether the data from week 2 and after for 2015 playoffs are not there.  I just wanted to make sure that I am not doing something wrong.  

I tried to download the data for the divisional round but I am getting the following:

>>> k = nflgame.games(2015, week=2, kind='POST')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/nflgame/__init__.py", line 228, in games
    return list(games_gen(year, week, home, away, kind, started))
TypeError: 'NoneType' object is not iterable

**Comment by ochawkeye** [comment]
Working here...

```python
>>> import nflgame
>>> k = nflgame.games(2015, week=2, kind='POST')
>>> for game in k:
...     print game
...
```
```bash
KC (20) at NE (27)
GB (20) at ARI (26)
SEA (24) at CAR (31)
PIT (16) at DEN (23)
```

This same issue has been reported a few times in different ways.  A schedule rebuild may knock this loose (just a guess).

On your system, I believe `update_sched.py` runs from the following:
`python c:\Python27\Lib\site-packages\nflgaem\update_sched.py --rebuild --year 2015 --phase POST`

If that fixes your problem please let me know!

**Comment by kpelechrinis** [comment]
Thanks; I' ve tried that and unfortunately has not fixed it... :(

**Comment by BurntSushi** [comment]
Also make sure `nflgame` is up to date.

**Comment by ochawkeye** [comment]
And just to confirm what `nflgame` is telling us...

```bash
C:\Users\Ben>dir d:\Python27\Lib\site-packages\nflgame\gamecenter-json\2016011*
 Volume in drive D has no label.
 Volume Serial Number is 1A1D-2527

 Directory of d:\Python27\Lib\site-packages\nflgame\gamecenter-json

01/10/2016  03:03 PM            12,470 2016011000.json.gz
01/10/2016  07:12 PM            14,949 2016011001.json.gz
01/16/2016  06:51 PM            14,296 2016011600.json.gz
01/16/2016  10:39 PM            13,417 2016011601.json.gz
01/17/2016  03:17 PM            13,537 2016011700.json.gz
01/17/2016  06:50 PM            13,524 2016011701.json.gz
               6 File(s)         82,193 bytes
               0 Dir(s)  128,133,574,656 bytes free
```

`2016011600`, `2016011601`, `2016011700`, and `2016011701` are the four games of week 2.  You're missing those four games, correct?

And you are running current version of `nflgame`?
```python
>>> nflgame.__version__
```
```bash
'1.2.19'
```

**Comment by kpelechrinis** [comment]
Quiet interestingly, I have these files under the gamecenter-json directory (and I am running the 1.2.19 version of nflagame as well).  For some reason it seems that it cannot find them.  I will check this issue and see if I can figure it out.

**Comment by drwofle21** [comment]
Was this fixed? If so how? I can access week one and week three data, but I can not access week two.

**Comment by kpelechrinis** [comment]
No unfortunately it was not fixed.  Honestly though I did not have much time to look into it.  I will keep you post it! In the meantime if someone has any other suggestion throw it out there.

**Comment by hpadmanabhan** [comment]
I ran into this same issue on a Linux box and was able to eventually independently resolve it with the same resolution that  @ochawkeye enumerated above of manually rebuilding the postseason schedule with update_sched.py.
