### ISSUE TITLE
nflgame-update-players --full-scan Error

### ISSUE THREAD

**Issue by ochawkeye** [BurntSushi/nflgame#202]
Running a `--full-scan` with `nflgame-update-players` results in the following error:

```
Loading players in games since 2009, this may take a while...
Traceback (most recent call last):
  File "d:\Python27\Scripts\nflgame-update-players", line 4, in <module>
    nflgame.update_players.run()
  File "D:\Python27\lib\site-packages\nflgame\update_players.py", line 360, in run
    for _, schedule in nflgame.sched.games.itervalues():
ValueError: too many values to unpack
```

**Comment by JessePresnell** [comment]
Having the same error now--is the solution changing .itervalues() to .iteritems()?

**Comment by ochawkeye** [comment]
Yes.  Either 
`for _, schedule in nflgame.sched.games.iteritems():` or 
`for schedule in nflgame.sched.games.itervalues():` should fix `--full-scan` for you.
