### ISSUE TITLE
2016 Preseason AttributeError 

### ISSUE THREAD

**Issue by cphipps** [BurntSushi/nflgame#226]
I followed Issue #220 to update 2016 pre/reg schedule.  When I run my code on 2015 I still get the output I expect.  When I run the code with "games = nflgame.games(2016, 1, kind="PRE")" I get the error below.  Is there any reason 2016 preseason would not include all the attributes 2015 regular season does?

CODE SNIPPET
for pos in ["QB"]:
    for p in [x for x in players.passing().sort("team") if x.player.position == pos]:

ERROR OUTPUT
Traceback (most recent call last):
    for p in [x for x in players.passing().sort("team") if x.player.position == pos]:
AttributeError: 'NoneType' object has no attribute 'position'

Thanks in advance.

Corey

**Comment by benschroeder** [comment]
I've reconstructed your code based on what you're probably seeing.
```python
import nflgame
games = nflgame.games(2016, kind='PRE')
players = nflgame.combine_max_stats(games)
for pos in ["QB"]:
    for p in [x for x in players.passing().sort("team") if x.player.position == pos]:
        print p
```

- Looks like your schedule is up to date, otherwise, you would have received an error like this when you tried to access the 2016 preseason games:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\nflgame\__init__.py", line 228, in games
    return list(games_gen(year, week, home, away, kind, started))
TypeError: 'NoneType' object is not iterable
```

- List comprehensions in Python are great, but they do make it a bit tougher to isolate where your error is coming from.  So I'm going to dummy down your list comprehension and build it back up so we can find the problem.

```python
import nflgame
games = nflgame.games(2016, kind='PRE')
players = nflgame.combine_max_stats(games)
#for pos in ["QB"]:
#    for p in [x for x in players.passing().sort("team") if x.player.position == pos]:
#        print p
for p in players:
	print p
```
Prints out a list of 2117 players.  So far so good.

```python
import nflgame
games = nflgame.games(2016, kind='PRE')
players = nflgame.combine_max_stats(games)
#for pos in ["QB"]:
#    for p in [x for x in players.passing().sort("team") if x.player.position == pos]:
#        print p
for p in players.passing().sort('team'):
	print p
```
Prints out a list of 107 players with passing type statistics.  Still good.

```python
import nflgame
games = nflgame.games(2016, kind='PRE')
players = nflgame.combine_max_stats(games)
#for pos in ["QB"]:
#    for p in [x for x in players.passing().sort("team") if x.player.position == pos]:
#        print p
for p in players.passing().sort('team'):
	if p.player.position == 'QB':
		print p
```
Hmm.  Here we got two players printed but then hit your `AttributeError`.

It seems a certain 'N.Sudfeld' appeared in a game, but doesn't have any meta data in nflgame.

There is a script included with `nflgame` that tries to update all of the players on current rosters.
```
c:> python c:\Python27\Scripts\nflgame-update-players
Loading games for PRE 2016 week 3
Downloading team rosters...
32/32 complete. (100.00%)
Done!
Fetching GSIS identifiers for players not in nflgame...
766/846 complete. (90.54%)
```

Now, running that same bit of code above goes a bit further.  I now get 48 QBs printed before I hit guys on the LA roster.  If you haven't manually added that team to `nflgame`, then it doesn't know where to find the roster page to populate the metadata for all of the players.

So off to `..\nflgame\__init__.py` to add in LA to `teams`.

Ran `nflgame-update-players` again and then re-ran the code above.  Now I get 56 QBs printed out before I start hitting guys on the JAC roster.  JAC changed to JAX a couple of years ago, but until recently nfl.com was redirecting requests to the JAC roster page to the JAX roster page.  Now they quit doing that.  I'm not sure of the official @BurntSushi was of fixing this, but one way is to change the JAC line in `..\nflgame\__init.py__` from JAC to JAX.

Ran `nflgame-update-players` one last time and then ran the code above...and I get 107 QBs printed out.

Hope this helps.

**Comment by ochawkeye** [comment]
I've reconstructed your code based on what you're probably seeing.
```python
import nflgame
games = nflgame.games(2016, kind='PRE')
players = nflgame.combine_max_stats(games)
for pos in ["QB"]:
    for p in [x for x in players.passing().sort("team") if x.player.position == pos]:
        print p
```

- Looks like your schedule is up to date, otherwise, you would have received an error like this when you tried to access the 2016 preseason games:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\nflgame\__init__.py", line 228, in games
    return list(games_gen(year, week, home, away, kind, started))
TypeError: 'NoneType' object is not iterable
```

- List comprehensions in Python are great, but they do make it a bit tougher to isolate where your error is coming from.  So I'm going to dummy down your list comprehension and build it back up so we can find the problem.

```python
import nflgame
games = nflgame.games(2016, kind='PRE')
players = nflgame.combine_max_stats(games)
#for pos in ["QB"]:
#    for p in [x for x in players.passing().sort("team") if x.player.position == pos]:
#        print p
for p in players:
	print p
```
Prints out a list of 2117 players.  So far so good.

```python
import nflgame
games = nflgame.games(2016, kind='PRE')
players = nflgame.combine_max_stats(games)
#for pos in ["QB"]:
#    for p in [x for x in players.passing().sort("team") if x.player.position == pos]:
#        print p
for p in players.passing().sort('team'):
	print p
```
Prints out a list of 107 players with passing type statistics.  Still good.

```python
import nflgame
games = nflgame.games(2016, kind='PRE')
players = nflgame.combine_max_stats(games)
#for pos in ["QB"]:
#    for p in [x for x in players.passing().sort("team") if x.player.position == pos]:
#        print p
for p in players.passing().sort('team'):
	if p.player.position == 'QB':
		print p
```
Hmm.  Here we got two players printed but then hit your `AttributeError`.

It seems a certain 'N.Sudfeld' appeared in a game, but doesn't have any meta data in nflgame.

There is a script included with `nflgame` that tries to update all of the players on current rosters.
```
c:> python c:\Python27\Scripts\nflgame-update-players
Loading games for PRE 2016 week 3
Downloading team rosters...
32/32 complete. (100.00%)
Done!
Fetching GSIS identifiers for players not in nflgame...
766/846 complete. (90.54%)
```

Now, running that same bit of code above goes a bit further.  I now get 48 QBs printed before I hit guys on the LA roster.  If you haven't manually added that team to `nflgame`, then it doesn't know where to find the roster page to populate the metadata for all of the players.

So off to `..\nflgame\__init__.py` to add in LA to `teams`.

Ran `nflgame-update-players` again and then re-ran the code above.  Now I get 56 QBs printed out before I start hitting guys on the JAC roster.  JAC changed to JAX a couple of years ago, but until recently nfl.com was redirecting requests to the JAC roster page to the JAX roster page.  Now they quit doing that.  I'm not sure of the official @BurntSushi was of fixing this, but one way is to change the JAC line in `..\nflgame\__init.py__` from JAC to JAX.

Ran `nflgame-update-players` one last time and then ran the code above...and I get 107 QBs printed out.

Hope this helps.

**Comment by cphipps** [comment]
Thanks much ochawkeye.  This got me to 59 QB but I still get the attribute error.  Below is the in the _init_.py file is how I edited team.

-Added LA
-Replaced JAC with JAX
-Commented out STL

Anything else you see I am doing wrong that would cause the attribute error?  Thanks

teams = [
    ['ARI', 'Arizona', 'Cardinals', 'Arizona Cardinals'],
    ['ATL', 'Atlanta', 'Falcons', 'Atlanta Falcons'],
    ['BAL', 'Baltimore', 'Ravens', 'Baltimore Ravens'],
    ['BUF', 'Buffalo', 'Bills', 'Buffalo Bills'],
    ['CAR', 'Carolina', 'Panthers', 'Carolina Panthers'],
    ['CHI', 'Chicago', 'Bears', 'Chicago Bears'],
    ['CIN', 'Cincinnati', 'Bengals', 'Cincinnati Bengals'],
    ['CLE', 'Cleveland', 'Browns', 'Cleveland Browns'],
    ['DAL', 'Dallas', 'Cowboys', 'Dallas Cowboys'],
    ['DEN', 'Denver', 'Broncos', 'Denver Broncos'],
    ['DET', 'Detroit', 'Lions', 'Detroit Lions'],
    ['GB', 'Green Bay', 'Packers', 'Green Bay Packers', 'G.B.', 'GNB'],
    ['HOU', 'Houston', 'Texans', 'Houston Texans'],
    ['IND', 'Indianapolis', 'Colts', 'Indianapolis Colts'],
    ['JAX', 'Jacksonville', 'Jaguars', 'Jacksonville Jaguars'],
    ['KC', 'Kansas City', 'Chiefs', 'Kansas City Chiefs', 'K.C.', 'KAN'],
    ['LA', 'Los Angeles', 'Rams', 'Los Angeles Rams'],
    ['MIA', 'Miami', 'Dolphins', 'Miami Dolphins'],
    ['MIN', 'Minnesota', 'Vikings', 'Minnesota Vikings'],
    ['NE', 'New England', 'Patriots', 'New England Patriots', 'N.E.', 'NWE'],
    ['NO', 'New Orleans', 'Saints', 'New Orleans Saints', 'N.O.', 'NOR'],
    ['NYG', 'Giants', 'New York Giants', 'N.Y.G.'],
    ['NYJ', 'Jets', 'New York Jets', 'N.Y.J.'],
    ['OAK', 'Oakland', 'Raiders', 'Oakland Raiders'],
    ['PHI', 'Philadelphia', 'Eagles', 'Philadelphia Eagles'],
    ['PIT', 'Pittsburgh', 'Steelers', 'Pittsburgh Steelers'],
    ['SD', 'San Diego', 'Chargers', 'San Diego Chargers', 'S.D.', 'SDG'],
    ['SEA', 'Seattle', 'Seahawks', 'Seattle Seahawks'],
    ['SF', 'San Francisco', '49ers', 'San Francisco 49ers', 'S.F.', 'SFO'],
    #['STL', 'St. Louis', 'Rams', 'St. Louis Rams', 'S.T.L.'],
    ['TB', 'Tampa Bay', 'Buccaneers', 'Tampa Bay Buccaneers', 'T.B.', 'TAM'],
    ['TEN', 'Tennessee', 'Titans', 'Tennessee Titans'],
    ['WAS', 'Washington', 'Redskins', 'Washington Redskins', 'WSH'],
]

**Comment by cphipps** [comment]
It looks like it gets some of the JAX QBs but then stops.  I ran a debug and it looks like Max Wittek uses the old JAC.  I think that may be why it is stopping.

Under Teams I have below but still no luck.  Any reason why this player uses JAC instead of JAX and if this is the reason I get the attribute error?  Is there a work around for this?  Thanks

    ['JAX', 'Jacksonville', 'Jaguars', 'Jacksonville Jaguars', 'JAC'],

![jac](https://cloud.githubusercontent.com/assets/13665549/17991952/c12216be-6b08-11e6-9a5a-62ffed38a37b.jpg)

**Comment by cphipps** [comment]
It looks like that is the issue.  I called used the code below to use only Week 1 preseason and get all the teams QBs.  Matt Wittek (Who the hell is this guy any way!) only played in Week 2.  I only get the error when running Week 2 or 2016 Preseason.  So the question is how to fix it?  Even with JAC under Teams I still get the error because his team is set to JAC.

games = nflgame.games(2016, 1, kind='PRE')

['JAX', 'Jacksonville', 'Jaguars', 'Jacksonville Jaguars', 'JAC'],

**Comment by ochawkeye** [comment]
You might be chasing a red herring there.  You're looking at `p.team`.  That does not reflect that player's meta data.  His meta data - the data that gets populated from the team roster page - is all stored in `p.player.XXX` (ie. `p.player.team`).  Running the code above and the following code works just fine on my side.  Did you run the `nflgame-update-players` script after all of your changes?

```python
import nflgame
games = nflgame.games(2016, kind='PRE')
players = nflgame.combine_max_stats(games)
for p in players.passing().sort('team'):
	if p.player.position == 'QB' and p.player.team in ['JAC', 'JAX']:
		print p, p.team, p.player.team
```
```
B.Bortles JAC JAX
C.Henne JAC JAX
B.Allen JAC JAX
M.Wittek JAC JAX
```

But you have uncovered something I was not aware of.  Whereas nfl.com no longer refers to Jacksonville as `JAC` on their roster page (http://www.nfl.com/teams/roster?team=JAC redirects to http://www.nfl.com/teams/roster?team=JAX), they are still referring to them as JAC on the game pages.

```python
import nflgame
games = nflgame.games(2016, kind='PRE')
for game in games:
	print game
```
```
...
JAC (13) at NYJ (17)
...
TB (27) at JAC (21)
...
```
That home team name in the second example comes from [here](https://github.com/BurntSushi/nflgame/blob/master/nflgame/game.py#L269).  Popping open the JSON from that game 2016082053.json.gz shows
```json
{"2016082053":
  {"home":
    {"score":
      {"1":7,"2":7,"3":0,"4":7,"5":0,"T":21},
    "abbr":"JAC",
    "to":0,
    "stats"...
```

Someone smarter than me might need to comment on this inconsistency as I'm not entirely sure if it has all that much of an impact on things.

**Comment by cphipps** [comment]
Yes I ran nflgame-player-update.  Below is the output.

![nflgame-update-players](https://cloud.githubusercontent.com/assets/13665549/18003189/de21623a-6b51-11e6-9e62-5723ddd54ea8.jpg)

I then put in the exact code you provided as seen below.

import nflgame
games = nflgame.games(2016, kind='PRE')
players = nflgame.combine_max_stats(games)
for p in players.passing().sort('team'):
    if p.player.position == 'QB' and p.player.team in ['JAC', 'JAX']:
        print p, p.team, p.player.team

I still get the attribute error due to  Wittek as seen below.

![attribue error](https://cloud.githubusercontent.com/assets/13665549/18003274/3ee279ce-6b52-11e6-81c8-658fe2ff9880.jpg)

Thanks for your help.

Corey

**Comment by ochawkeye** [comment]
Ironically, it looks like our buddy Max got cut since yesterday, or at least he was removed from the roster on nfl.com between yesterday morning and this morning.

I now see that his meta data is gone on my side as well, though I do not get the `AttributeError` that you are seeing.  Your code should still be able to run despite him no longer being on the roster.  Heck, half of the guys that played in preseason games in 2012 are long gone from the league and the code should still work.

```python
import nflgame
games = nflgame.games(2012, kind='PRE')
players = nflgame.combine_max_stats(games)

for p in players.passing().sort('team'):
	print '\t', p, p.team, p.player.team, p.player
	if p.player.position == 'QB' and p.player.team in ['JAC', 'JAX']:
		print p, p.team, p.player.team, p.player.years_pro
```
```
        R.Griffin WAS CLE Robert Griffin III (QB, CLE)
        R.Grossman WAS  Rex Grossman (, )
        K.Cousins WAS WAS Kirk Cousins (QB, WAS)
        J.Crompton WAS  Jonathan Crompton (, )
        M.Hasselbeck TEN  Matt Hasselbeck (, )
        J.Locker TEN  Jake Locker (, )
        R.Smith TEN  Rusty Smith (, )
        N.Stephens TEN  Nick Stephens (, )
        J.Freeman TB  Josh Freeman (, )
        D.Orlovsky TB DET Dan Orlovsky (QB, DET)
        B.Ratliff TB  Brett Ratliff (, )
        S.Bradford STL PHI Sam Bradford (QB, PHI)
        K.Clemens STL SD Kellen Clemens (QB, SD)
        A.Davis STL CLE Austin Davis (QB, CLE)
        T.Brandstater STL  Tom Brandstater (, )
        A.Smith SF KC Alex Smith (QB, KC)
        C.Kaepernick SF SF Colin Kaepernick (QB, SF)
        S.Tolzien SF IND Scott Tolzien (QB, IND)
        J.Johnson SF BAL Josh Johnson (QB, BAL)
        M.Flynn SEA  Matt Flynn (, )
        R.Wilson SEA SEA Russell Wilson (QB, SEA)
        J.Portis SEA  Josh Portis (, )
        T.Jackson SEA  Tarvaris Jackson (, )
        P.Rivers SD SD Philip Rivers (QB, SD)
        J.Lee SD  Jarrett Lee (, )
        C.Whitehurst SD  Charlie Whitehurst (, )
        B.Roethlisberger PIT PIT Ben Roethlisberger (QB, PIT)
        B.Leftwich PIT  Byron Leftwich (, )
        J.Johnson PIT BAL Jerrod Johnson (QB, BAL)
        C.Batch PIT  Charlie Batch (, )
        M.Vick PHI  Mike Vick (, )
        M.Kafka PHI  Mike Kafka (, )
        N.Foles PHI KC Nick Foles (QB, KC)
        T.Edwards PHI  Trent Edwards (, )
        C.Palmer OAK ARI Carson Palmer (QB, ARI)
        M.Leinart OAK  Matt Leinart (, )
        T.Pryor OAK CLE Terrelle Pryor (WR, CLE)
        M.Sanchez NYJ DEN Mark Sanchez (QB, DEN)
        T.Tebow NYJ  Tim Tebow (, )
        G.McElroy NYJ  Greg McElroy (, )
        M.Simms NYJ ATL Matt Simms (QB, ATL)
        E.Manning NYG NYG Eli Manning (QB, NYG)
        D.Carr NYG  David Carr (, )
        R.Perrilloux NYG  Ryan Perrilloux (, )
        D.Brees NO NO Drew Brees (QB, NO)
        C.Daniel NO PHI Chase Daniel (QB, PHI)
        S.Canfield NO  Sean Canfield (, )
        L.McCown NO NO Luke McCown (QB, NO)
        T.Brady NE NE Tom Brady (QB, NE)
        B.Hoyer NE CHI Brian Hoyer (QB, CHI)
        R.Mallett NE BAL Ryan Mallett (QB, BAL)
        C.Ponder MIN SF Christian Ponder (QB, SF)
        J.Webb MIN CAR Joe Webb (QB, CAR)
        M.Bethel-Thompson MIN PHI McLeod Bethel-Thompson (QB, PHI)
        S.Rosenfels MIN  Sage Rosenfels (, )
        Matt.Moore MIA MIA Matt Moore (QB, MIA)
        R.Tannehill MIA MIA Ryan Tannehill (QB, MIA)
        P.Devlin MIA  Pat Devlin (, )
        M.Cassel KC TEN Matt Cassel (QB, TEN)
        B.Quinn KC  Brady Quinn (, )
        R.Stanzi KC  Ricky Stanzi (, )
        A.Tanney KC TEN Alex Tanney (QB, TEN)
        B.Gabbert JAC SF Blaine Gabbert (QB, SF)
        C.Henne JAC JAX Chad Henne (QB, JAX)
C.Henne JAC JAX 9
        J.Palmer JAC  Jordan Palmer (, )
        A.Luck IND IND Andrew Luck (QB, IND)
        D.Stanton IND ARI Drew Stanton (QB, ARI)
        C.Harnish IND  Chandler Harnish (, )
        M.Schaub HOU ATL Matt Schaub (QB, ATL)
        T.Yates HOU  T.J. Yates (, )
        J.Beck HOU  John Beck (, )
        C.Keenum HOU LA Case Keenum (QB, LA)
        A.Rodgers GB GB Aaron Rodgers (QB, GB)
        G.Harrell GB  Graham Harrell (, )
        B.Coleman GB  B.J. Coleman (, )
        M.Stafford DET DET Matthew Stafford (QB, DET)
        Sh.Hill DET MIN Shaun Hill (QB, MIN)
        K.Moore DET DAL Kellen Moore (QB, DAL)
        P.Manning DEN  Peyton Manning (, )
        C.Hanie DEN  Caleb Hanie (, )
        B.Osweiler DEN HOU Brock Osweiler (QB, HOU)
        A.Weber DEN  Adam Weber (, )
        T.Romo DAL DAL Tony Romo (QB, DAL)
        K.Orton DAL  Kyle Orton (, )
        S.McGee DAL  Stephen McGee (, )
        R.Carpenter DAL  Rudy Carpenter (, )
        B.Weeden CLE HOU Brandon Weeden (QB, HOU)
        C.McCoy CLE WAS Colt McCoy (QB, WAS)
        S.Wallace CLE  Seneca Wallace (, )
        T.Lewis CLE SF Thad Lewis (QB, SF)
        A.Dalton CIN CIN Andy Dalton (QB, CIN)
        B.Gradkowski CIN PIT Bruce Gradkowski (QB, PIT)
        Z.Robinson CIN  Zac Robinson (, )
        T.Hansen CIN  Tyler Hansen (, )
        J.Campbell CHI  Jason Campbell (, )
        J.McCown CHI CLE Josh McCown (QB, CLE)
        M.Blanchard CHI  Matt Blanchard (, )
        J.Cutler CHI CHI Jay Cutler (QB, CHI)
        C.Newton CAR CAR Cam Newton (QB, CAR)
        D.Anderson CAR CAR Derek Anderson (QB, CAR)
        J.Clausen CAR  Jimmy Clausen (, )
        R.Fitzpatrick BUF NYJ Ryan Fitzpatrick (QB, NYJ)
        T.Thigpen BUF  Tyler Thigpen (, )
        V.Young BUF  Vince Young (, )
        B.Smith BUF  Brad Smith (, )
        J.Flacco BAL BAL Joe Flacco (QB, BAL)
        T.Taylor BAL BUF Tyrod Taylor (QB, BUF)
        C.Painter BAL  Curtis Painter (, )
        C.Stewart BAL  Chester Stewart (, )
        M.Ryan ATL ATL Matt Ryan (QB, ATL)
        C.Redman ATL  Chris Redman (, )
        J.Wilson ATL  John Parker Wilson (, )
        Do.Davis ATL  Dominique Davis (, )
        K.Kolb ARI  Kevin Kolb (, )
        J.Skelton ARI  John Skelton (, )
        R.Bartel ARI  Richard Bartel (, )
        R.Lindley ARI  Ryan Lindley (, )
```

**Comment by ochawkeye** [comment]
Well...while that worked fine for me for 2012 it didn't fare so well for 2009.  Mr. "A.Mortensen" made mine puke with your same `AttributeError: 'NoneType' object has no attribute 'position'`.

```
J.Campbell Jason Campbell (, ) 
	Team then: WAS
	Team now: no longer in the league
T.Collins Todd Collins (, ) 
	Team then: WAS
	Team now: no longer in the league
M.Kelly Malcolm Kelly (, ) 
	Team then: WAS
	Team now: no longer in the league
C.Brennan Colt Brennan (, ) 
	Team then: WAS
	Team now: no longer in the league
C.Daniel Chase Daniel (QB, PHI) QB
	Team then: WAS
	Team now: PHI
A.Mortensen None
Traceback (most recent call last):
  File "C:\Users\schroedb\Documents\GitHub\cphipps.py", line 7, in <module>
    print p, p.player, p.player.position
AttributeError: 'NoneType' object has no attribute 'position'
```
[confused shrug]

**Comment by cphipps** [comment]
Thanks for looking into it.  I guess during the regular season I will just have to hope I do not run into it.
