### ISSUE TITLE
Error loading nflgame

### ISSUE THREAD

**Issue by gocartracer** [BurntSushi/nflgame#301]
>>> import nflgame
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\nflgame\__init__.py", line 97, in <module>
    import nflgame.game  # noqa
  File "C:\Python27\lib\site-packages\nflgame\game.py", line 12, in <module>
    import nflgame.sched
  File "C:\Python27\lib\site-packages\nflgame\sched.py", line 47, in <module>
    games, last_updated = _create_schedule()
  File "C:\Python27\lib\site-packages\nflgame\sched.py", line 40, in _create_schedule
    year, week = nflgame.live.current_year_and_week()
AttributeError: 'module' object has no attribute 'live'

How to I fix this

**Comment by derek-adair** [comment]
You need to provide more information, posting an error is not enough.

- Post your code
- your configuration environment.
