### ISSUE TITLE
Intermittent socket time out error on nfl-player-update

### ISSUE THREAD

**Issue by codeglider** [BurntSushi/nflgame#310]
Loading games for PRE 2017 week 1
Finding (profile id -> gsis id) mapping for players...
96/422 complete. (22.75%)Traceback (most recent call last):
  File "/usr/local/bin/nflgame-update-players", line 4, in <module>
    nflgame.update_players.run()
  File "/usr/local/lib/python2.7/dist-packages/nflgame/update_players.py", line 386, in run
    for i, t in enumerate(pool.imap(fetch, players.items()), 1):
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
socket.timeout: timed out
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 113, in worker
  File "/usr/local/lib/python2.7/dist-packages/nflgame/update_players.py", line 385, in fetch
  File "/usr/local/lib/python2.7/dist-packages/nflgame/update_players.py", line 107, in profile_url
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1659, in request
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1399, in _request
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1356, in _conn_request
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'BadStatusLine'
ramon_rahman@fantisserie-0a1:/usr/local/lib/python2.7/dist-packages/nflgame$ sudo nflgame-update-players
Loading games for PRE 2017 week 1
Finding (profile id -> gsis id) mapping for players...
108/422 complete. (25.59%)Traceback (most recent call last):
  File "/usr/local/bin/nflgame-update-players", line 4, in <module>
    nflgame.update_players.run()
  File "/usr/local/lib/python2.7/dist-packages/nflgame/update_players.py", line 386, in run
    for i, t in enumerate(pool.imap(fetch, players.items()), 1):
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
socket.timeout: timed out

**Comment by BurntSushi** [comment]
This issue isn't actionable. Looks like a connectivity problem.

**Comment by ochawkeye** [comment]
Just a note that I witnessed this as well.  Agree that it's not `nflgame` responsibility, though catching the exception might make for a more friendly interaction with the user.

```
D:\Python27\Scripts>python nfldb-update
-------------------------------------------------------------------------------
STARTING NFLDB UPDATE AT 2017-08-18 09:00:06.833000
Connecting to nfldb... done.
Setting timezone to UTC... done.
Updating player JSON database... (last update was 2017-08-15 07:30:12.952000+00:00)
Loading games for PRE 2017 week 2
Finding (profile id -> gsis id) mapping for players...
22/22 complete. (100.00%)
Done!
Downloading team rosters...
32/32 complete. (100.00%)
Done!
Fetching GSIS identifiers for players not in nflgame...
154/225 complete. (68.44%)Traceback (most recent call last):
  File "D:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Python27\lib\site-packages\nflgame\update_players.py", line 501, in <module>
    run()
  File "D:\Python27\lib\site-packages\nflgame\update_players.py", line 436, in run
    for i, (purl, gid) in enumerate(pool.imap(fetch, purls), 1):
  File "D:\Python27\lib\multiprocessing\pool.py", line 659, in next
    raise value
socket.timeout: timed out
`D:\Python27\python.exe -m nflgame.update_players --no-block` failed (exit status 1)
done.
Locking player table...
Updating 7666 players... done.
Locking write access to tables... done.
Updating season phase, year and week... done.
Bulk inserting data for 20 games...
        Sending batch of data to database.
        Sending batch of data to database.
        Sending batch of data to database.
        Sending batch of data to database.
...
```
