### ISSUE TITLE
Nonetype Error on Update Players

### ISSUE THREAD

**Issue by JessePresnell** [BurntSushi/nflgame#326]
Ran into #316 earlier and also needed to update my __init__.py file to add the LA Chargers line per BurntSushi/nfldb#252 and now I'm getting the following error when trying to run

``>>> python nflgame-update-players``

Loading games for POST 2016 week 5
Downloading team rosters...
1/33 complete. (3.03%)Traceback (most recent call last):
  File "nflgame-update-players", line 4, in <module>
    nflgame.update_players.run()
  File "C:\Python27\lib\site-packages\nflgame\update_players.py", line 415, in run
    tbodys = soup.find(id='result').find_all('tbody')
AttributeError: 'NoneType' object has no attribute 'find_all'

So far I've:

- Uninstalled nflgame via pip and reinstalled directly from the git file per #325 
- Ran nfldb-update successfully

Any suggestions on what may be the culprit?

**Comment by ochawkeye** [comment]
You mention that `nfldb-update` ran successfully, but `nfldb-update` [invokes](https://github.com/BurntSushi/nfldb/blob/9cc2fe8280cada7c1595d54e4dc698b99da72a40/nfldb/update.py#L145)  `nflgame-update-players`.  

Is this an issue you continue to see when attempting to re-run `nflgame-update-players`?

**Comment by JessePresnell** [comment]
@ochawkeye that's correct. This is when specifically invoking nflgame-update-players

**Comment by JessePresnell** [comment]
@ochawkeye actually, it looks like nfldb-update is now failing with the same error.

**Comment by colemani45** [comment]
I'm also having the same problem

**Comment by JessePresnell** [comment]
Hey @ochawkeye any idea why changing the PARSER object in line 129 of nflgame/update_players.py  makes things work? Seems lxml parsing throws out all the HTML from the `content` object?

From this
```def roster_soup(team):
    resp, content = new_http().request(urls['roster'] % team, 'GET')
    eprint(content)
    if resp['status'] != '200':
        return None
    return BeautifulSoup(content, PARSER)```

To this:
```def roster_soup(team):
    resp, content = new_http().request(urls['roster'] % team, 'GET')
    eprint(content)
    if resp['status'] != '200':
        return None
    return BeautifulSoup(content, 'html.parser')```

**Comment by ochawkeye** [comment]
Certainly helps explain why I'm not seeing the issue.  From [`update_players.py`](https://github.com/BurntSushi/nflgame/blob/master/nflgame/update_players.py#L55-L63) in order the parser `nflgame` tries to use is `lxml.html`, `html5lib`, and `html.parser`.
```
D:\>python
Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import lxml.html
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named lxml.html
>>> import html5lib
>>>
```
I don't have `lxml.html` installed so presumably am using `html5lib` for the parser.

**Comment by tzane** [comment]
I just wanted to add that I am also having this same problem. I tried making the same modification to update_players.py as JessePresnell did above but still appear to have the same problem with soup as before only my traceback is slightly different:

.
.
.
.
Could not get roster for team TB
-------------------------------------------------------------------------------
Could not get roster for team TEN
-------------------------------------------------------------------------------
Could not get roster for team WAS
Exception in thread Thread-4 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 530, in __bootstrap_inner
  File "C:\Python27\lib\threading.py", line 483, in run
  File "C:\Python27\lib\multiprocessing\pool.py", line 272, in _handle_workers
<type 'exceptions.TypeError'>: 'NoneType' object is not callable


Would hugely appreciate any guidance if someone has made further progress on on this -- Thanks!

**Comment by ochawkeye** [comment]
That really doesn't look like the same error...
Your traceback is clipped, but it looks to me like `update_players.py` went through and failed to access the roster URL for all 32 teams (ie. http://www.nfl.com/teams/roster?team=TB).

I suspect it was not anticipated that `update_players.py` wouldn't be able to get to _any_ of the URLs.  Exception handling aside, are you able to get to a link like http://www.nfl.com/teams/roster?team=TB from that PC?

**Comment by tzane** [comment]
Hi @ochawkeye , yes I can definitely access the url.

**Comment by ochawkeye** [comment]
Maybe I'm barking up the wrong tree on this, but I'm still leaning toward you not being able to get to the urls.

Can you do this for me?  Open up a python interpreter in a terminal window / command prompt.
```
>>> from nflgame import update_players
>>> soup = update_players.roster_soup('TB')
>>> print len(soup)
7
>>> soup = update_players.roster_soup('FAKE')
>>> print len(soup)
2
```

**Comment by tzane** [comment]
My output:

>>> from nflgame import update_players
>>> soup = update_players.roster_soup('TB')
>>> print len(soup)
15
>>> soup = update_players.roster_soup('FAKE')
>>> print len(soup)
3

**Comment by ochawkeye** [comment]
Is the error you pasted above something that happens every time you run it?  Can you just try to run `update_players.py` again?
